---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "48"
year: "2026"
contributor: 
- Ulrike Wuttke
title: "Die Genese des Wissenschaftspodcasts <q>Die Wissensarchitekt*innen</q> – von der Idee ins Ohr"
abstract: "Dieser Beitrag präsentiert in Dialogform als fiktives Interview die Genese des Podcasts „Die Wissensarchitekt*innen“. Diese wird anhand der Punkte Motivation & Themenverständnis, Gesprächspartner*innen & Vorbereitung, Episodenstruktur & Dramaturgie, Technik & Tools und Rezeption, Feedback & Ausblick vorgestellt. Dabei werden sowohl spezifische inhaltliche Aspekte des Podcasts als auch Learnings für allgemein am Podcasting als Format der Wissenschaftskommunikation interessierte Personen erörtert."
pdf: "https://doi.org/10.18452/37898"
doi: "10.18452/37898"
date: 2026-07-15
comments: false
sharing: true
footer: true

---