---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "48"
year: "2026"
contributor: 
- Redaktion LIBREAS
title: "Editorial #48: Let’s talk. Interviews"
pdf: "main.pdf"
date: 2026-06-26
comments: false
sharing: true
footer: true

---