---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "48"
year: "2026"
contributor: 
- Alexandra Roth
title: "Qualitative Interviews und Forschungsethik"
abstract: "Mit qualitativen Interviews lassen sich unterschiedliche Fragestellungen bearbeiten. Die Methode konfrontiert Forschende allerdings mit einer Reihe ethischer Herausforderungen. Der Beitrag beschreibt Wertkonflikte, die sich bei Untersuchungen, die mithilfe qualitativer Interviews durchgeführt werden, ergeben können, und zeigt mögliche Lösungswege auf."
abstractalt: "Qualitative interviews can be used to address a wide range of research questions. However, the method confronts researchers with a number of ethical challenges. The article describes potential conflicts of values that can arise in studies using qualitative interviews and suggests possible solutions."
pdf: "https://doi.org/10.18452/37904"
doi: "10.18452/37904"
date: 2026-07-05
comments: false
sharing: true
footer: true

---