---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "48"
year: "2026"
contributor: 
- Dirk Wissen
- Linda Freyberg
title: "Auf einen Espresso mit Dirk Wissen"
pdf: "main.pdf"
abstract: "Interview geführt von Linda Freyberg an einem lauen Sommerabend am 3. Juni 2026 in Berlin-Friedrichshain. In BuB erschien seit 2015 monatlich die Interviewreihe <q>Wissen fragt … auf einen Espresso mit …</q>, in dessen Rahmen er 102 Interviews zum Thema <q>Atmosphäre von Bibliotheken</q> führte."
date: 2026-06-27
comments: false
sharing: true
footer: true

---