---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "48"
year: "2026"
contributor: 
- Maxi Kindling
- Ben Kaden
- Linda Freyberg
title: "Ein Gespräch mit den LIBREAS-Gründer*innen Maxi Kindling und Ben Kaden"
pdf: "main.pdf"
date: 2026-06-27
comments: false
sharing: true
footer: true

---