---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "48"
year: "2026"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #17 (Frühjahr 2026)"
pdf: "https://doi.org/10.18452/37907"
doi: "10.18452/37907"
date: 2026-07-17
comments: false
sharing: true
footer: true

---