---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "48"
year: "2026"
contributor: 
- Christine Gläser
- Ulrike Verch
- Karsten Schuldt
title: "Interview mit der Redaktion des API Magazin"
pdf: "main.pdf"
date: 2026-06-27
comments: false
sharing: true
footer: true

---