---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "48"
year: "2026"
contributor: 
- Kathrin Brannemann
- Josephine Kreutzer
title: "Mehr als Information: Interviews als Raum für Geschichten, Werte und Kultur"
pdf: "https://doi.org/10.18452/37899"
doi: "10.18452/37899"
date: 2026-07-15
comments: false
sharing: true
footer: true

---